---
title: "Explore S1pp Simulations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 8, fig.width = 6.5)
```

# Abstract

I explore the output from the S1 simulations with preferential pairing.

# Analysis

```{r, message=FALSE}
library(tidyverse)
library(ggthemes)
sdat <- as_data_frame(read.csv("../../../reproduce_genotyping/Output/sims_out/sims_out_pp.csv"))
```

# Ability to estimate preferential pairing

```{r}
sdat %>%
  select(s1pp_firstweight, firstweight, bias, od) ->
  smalldat

smalldat %>%
  ggplot(mapping = aes(x = factor(firstweight), y = s1pp_firstweight)) +
  geom_boxplot() +
  facet_grid(bias ~ od) +
  theme_bw() +
  theme(strip.background = element_rect(fill = "white")) +
  xlab("True Weight") +
  ylab("Estimated Weight") ->
  pl

pl

pdf(file = "../output/gatk_plots/est_weight_pp.pdf", 
    width = 6.5, height = 8, 
    family = "Times")
print(pl)
dev.off()
```


# Proportion correct of top 3 methods

```{r}
sdat %>%
  transmute(S1pp = 1 - s1pp_ham, S1 = 1 - s1_ham, fitPoly = 1 - fp_ham,
            od = od, bias = bias, weight = factor(firstweight)) %>%
  gather(key = "Method", value = "prop_correct", S1pp:fitPoly) ->
  subdat

subdat$Method <- factor(subdat$Method,levels = c("S1pp", "S1", "fitPoly"))

pl <- ggplot(data = subdat, 
       mapping = aes(x = weight, y = prop_correct, color = Method)) +
  facet_grid(bias ~ od) +
  geom_boxplot(outlier.size = 0.5) +
  theme_bw() +
  theme(strip.background = element_rect(fill = "white"),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  ggthemes::scale_color_colorblind() +
  xlab("Weight on 1") +
  ylab("Proportion Correct")

pl

pdf(file = "../output/gatk_plots/prop_correct_pp.pdf", 
    width = 6.5, height = 8, 
    family = "Times")
print(pl)
dev.off()
```

