---
title: "Speed Flexdog vs Updog"
author: "David Gerard"
date: "March 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

I showed [here](flexdog_v_updog.html) that `updog` with option `model = "hw"` is the same as `flexdog` with option `model = "hw"` in term of parameter estimates. Here, I show that `flexdog` is about 20 percent faster.

# Analysis

```{r, message=FALSE}
library(updog)
library(mupdog)
library(tidyverse)
```

```{r}
data("snpdat")
ploidy  <- 6
snpdat %>% 
  filter(snp == "SNP1") ->
  smalldat
refvec  <- smalldat$counts
refvec  <- refvec[!is.na(refvec)]
sizevec <- smalldat$size
sizevec <- sizevec[!is.na(sizevec)]
```

Parameter lists
```{r}
ulist <- list(ocounts      = refvec, 
              osize          = sizevec, 
              ploidy         = ploidy, 
              update_outprop = FALSE, 
              out_prop       = 0, 
              model          = "hw", 
              seq_error_mean = -4.7, 
              seq_error_sd   = 1, 
              bias_val_mean  = 0, 
              bias_val_sd    = 0.7)

flist <- list(refvec    = refvec, 
              sizevec   = sizevec, 
              ploidy    = ploidy, 
              model     = "hw",
              verbose   = FALSE, 
              mean_bias = 0,
              var_bias  = 0.7^2, 
              mean_seq  = -4.7, 
              var_seq   = 1,
              tol       = 10^-5)
```


Fit both `updog` and `flexdog` with the HW options.
```{r, cache=TRUE}
mout <- microbenchmark::microbenchmark(
  uout <- do.call(what = updog_vanilla, args = ulist),
  fout <- do.call(what = flexdog, args = flist)
)
```

```{r}
mout
```
