---
title: "Home"
output:
  html_document:
    toc: false
---

* [I think sufficient conditions are that R is psd and has diagonal entries less than or equal to 1.](check_0_1.html)
* [Exploring a new generalization of the BB to allow for correlation.](explore_mbb.html) The observations appear to be marginally beta-binomial, which is really cool. The sample correlation looks about the same as the "correlation" matrix used in the conditional distributions. 
* [The integral over the log BB density checks out](check_bb_integral.html)
* [mupdog looks pretty good for a first try!](try_mupdog_1.html) Interestingly, those inbreeding coefficients just don't matter.
* [mupdog still looks good when using 1000 Shirasawa SNPs](try_mupdog_1000.html). No major difference here than with using 500 SNPs.
* [When contrain correlations to be 0, inbreeding still estimated to be 0.](no_cor.html) Also, in high-bias SNP's, some of the genotyping seems a little off.
* [Benefits of fitting correlation mostly apparent in high-bias SNPs](compare_cor_nocor.html)
* [awesome results using the data from uidewilligen et al.](uitdewilligen.html) (1) The correlation matrix clearly clusters into two distinct groups. I wonder if there was a family in one group and the general population in the other. (2) High coverage SNPs look bad but moderate coverage SNP's look fantastic. Are the high-coverage SNP's due to something like copy number variation? (3) Inbreeding is more important in this non-sib population.
* [Looked at some filtering trends.](depth.html) It seems that there is a higher incidence of bad-SNPs at the higher covered SNPs. Some generous filters seem to keep mostly good-looking SNPs.
* [Individual 51 of the Uitdewilligen dataset has a super high od parameter on the genotypes.](weird_ind.html) I think its sample is corrupted. The readcounts always either all ref or all alt, even when all of the other individuals are all the other allele.
* [Cannot get empirical estimated correlation to match estimated correlation.](uit_corr.html)
* [When fitting without corr, get very different bias estimates and the genotyping results don't look good where they differ.](uitdewilligen_nocorr.html)
* [Assuming diploid when tetraploid to uitdewilligen data results in lower objective value](uitdewilligen_k2.html)
* [Assuming hexaploid when tetraploid to uitdewilligen data results in lower objective value](uitdewilligen_k6.html)
* [Adding correlation helps in mislabelings in Shirasawa data](shir_fix_corr.html)
* [I am updating the correlation matrix incorrectly.](corr_mle.html) I don't know yet how much this matters.
* [A non-1 variance biases the distribution away from $K\mu$. This would make the allele frequencies harder to interpret.](normal_bb.html)
* [Fit Shirasawa data without the covariance matrix constrained to be diagonal.](shirasawa_nodiag_constraint.html) Can pick out the parent easily.
* [You can understand the negative correlations by the fact that we are first removing the allele frequencies at each locus before calculating this correlation](shir_corr.html)
* [Oracle misclassification error rates](oracle_miss.html)
* [Oracle rates indicate that it's better to account for bias directly rather than use WASP (which decreases the sample size).](bias_or_remove.html)
* [Explore why updog does poorly on subset of data](why_does_updog_do_poorly.html)

# Looking at the `mupdog` distribution
* [The Gaussian Binomial can mimic the distribution of a convolution of two hypergeometrics in most cases, but it doesn't do as well when the same variance needs to be shared across loci](kl_div.html)

# Flexdog
* [`mupdog` works as well or better than `flexdog` in every SNP I try in the Shirasawa dataset](flexdog_try1.html). Note that `mupdog` is technically a mispecified model whereas `flexdog` is technically correctly specified (because the genotype distribution is unimodal). The problem seems to be that the bias parameter is estimated unstably. We need a better way to estimate it. Some sort of adaptive regularization?
* [`flexdog` with option `model = "hw"` is same as `updog` with option `model = "hw"`](flexdog_v_updog.html).
* [`flexdog` is slightly faster than `updog`](flex_v_up_speed.html)
* [Simple EM is faster than CVXR in unimodal update](compare_ash_cvxr.html)
* [Compare CVXR and EM implementations of flexdog](flexdog_try2.html)
* [`flexdog` with `model = "s1"` gives same results as `updog` with `model = "s1"` but is 3-6 times faster.](flexdog_v_updog_f1.html)
* [unimodal option relatively robust to penalty as long as it is large enough](ashpen.html)
* [BB od is estimated near 0 when truth is S1](try_bb_option_flexdog.html). This makes sense since F1 is even *less* dispersed than HWE.
* [Normal option doesn't work so well on SNP2](norm_flex.html)
* [Number of samples needed to genotype with 95\% accuracy](oracle_fig.html)
* [`flexdog` and `updog` match in terms of posterior summaries when using outliers](out_compare.html).
* [Check for errors in the `"ash"` option in `updog`](check_for_ash_updog_err.html).
* [Joint dist with oracle for small read-depth tetraploid](oracle_tetra_joint.html)
* [Relationship between read-depth and overdispersion estimates in shirasawa data](od_vs_rd.html).
* [See how various priors behave on uitdewilligen data](play_uit.html). The flex prior works well sometimes and sometimes works horribly.
* [See how the calls made by uit differ from the calls made by `updog`](uit_compare_variants.html)
* [Play around with the Rocher et al data that compares 454 with GBS](rocher_play.html)
* [Proof of concept that `vcfdog` works](vcfdog_test.html)
* [`updog` is faster than `ashr` in terms of weighted problem on small data](cvs_vs_em.html)

# fitPoly
* [Try `fitPoly` on the Shirasawa data](fit_poly_shir.html). It does just as well in genotyping, but the differences in precision estimates for each individual are very different.
* [In simulations, `updog` is better than `fitPoly` by many measures.](fitPoly_sim_play.html)
* [Example Shirasawa SNP where `updog` appears to perform much better than `fitPoly`](fitPoly_on_shir.html)
* [`updog` always does better using correlation as the metric](fitPoly_cor.html)

