---
title: "Try Norm Option in Flexdog"
author: "David Gerard"
date: "April 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

I try out the new `model = "norm"` option in `flexdog`.

It's not so good on SNP2.

# Analysis

```{r}
library(mupdog)
library(updog)
library(tidyverse)
data("snpdat")
snpdat %>%
  filter(snp == "SNP1") ->
  smalldat
refvec <- smalldat$counts
sizevec <- smalldat$size
ploidy <- 6
nout <- flexdog(refvec = refvec, sizevec = sizevec, ploidy = ploidy, model = "norm")
plot(nout)
plot(nout$gene_dist, type = "h")
```


```{r}
snpdat %>%
  filter(snp == "SNP2") ->
  smalldat
refvec <- smalldat$counts
sizevec <- smalldat$size
ploidy <- 6
nout <- flexdog(refvec = refvec, sizevec = sizevec, ploidy = ploidy, model = "norm")
plot(nout)
plot(nout$gene_dist, type = "h")
```

```{r}
snpdat %>%
  filter(snp == "SNP3") ->
  smalldat
refvec <- smalldat$counts
sizevec <- smalldat$size
ploidy <- 6
nout <- flexdog(refvec = refvec, sizevec = sizevec, ploidy = ploidy, model = "norm")
plot(nout)
plot(nout$gene_dist, type = "h")
```

